language: node_js
node_js:
  - "node"
  - "8"

addons:
    code_climate:
        repo_token: NODE_ENV=CODECLIMATETOKEN

env:
  - NODE_ENV=test

before_script:
  - chmod 0777 ./node_modules/.bin/mocha

script: 
  - npm run test:server 

after_success:
  - npm run coveralls
  - npm run codeclimate